// <auto-generated />
using System;
using GoldLoanFinance.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GoldLoanFinance.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251021150021_keyReferenceCorrection")]
    partial class keyReferenceCorrection
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GoldLoanFinance.Domain.Entities.Bank", b =>
                {
                    b.Property<int>("BankId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BankId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("BankId");

                    b.ToTable("Banks");

                    b.HasData(
                        new
                        {
                            BankId = 1,
                            Name = "HNB"
                        },
                        new
                        {
                            BankId = 2,
                            Name = "ABC"
                        });
                });

            modelBuilder.Entity("GoldLoanFinance.Domain.Entities.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("NIC")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            NIC = "856987452v",
                            Name = "Prashath",
                            Phone = "0715689562"
                        },
                        new
                        {
                            CustomerId = 2,
                            NIC = "895698236v",
                            Name = "Ranmini",
                            Phone = "0715458533"
                        });
                });

            modelBuilder.Entity("GoldLoanFinance.Domain.Entities.LoanDetails", b =>
                {
                    b.Property<int>("ArticleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ArticleId"));

                    b.Property<string>("ArticleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LoanId")
                        .HasColumnType("int");

                    b.Property<long>("Unit")
                        .HasColumnType("bigint");

                    b.HasKey("ArticleId");

                    b.HasIndex("LoanId");

                    b.ToTable("LoanDetails");

                    b.HasData(
                        new
                        {
                            ArticleId = 1,
                            ArticleName = "Ring",
                            LoanId = 1,
                            Unit = 1L
                        });
                });

            modelBuilder.Entity("GoldLoanFinance.Domain.Entities.LoanMaster", b =>
                {
                    b.Property<int>("LoanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LoanId"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateTaken")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("DueDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("DATEADD(year,1,GETDATE())");

                    b.Property<bool>("IsPledgedToBank")
                        .HasColumnType("bit");

                    b.Property<decimal>("LoanAmount")
                        .HasPrecision(15, 5)
                        .HasColumnType("decimal(15,5)");

                    b.HasKey("LoanId");

                    b.HasIndex("CustomerId");

                    b.ToTable("LoanMaster");

                    b.HasData(
                        new
                        {
                            LoanId = 1,
                            CustomerId = 1,
                            DateTaken = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPledgedToBank = false,
                            LoanAmount = 150.00m
                        });
                });

            modelBuilder.Entity("GoldLoanFinance.Domain.Entities.RepledgeDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ArticleId")
                        .HasColumnType("int");

                    b.Property<int>("RepledgeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId");

                    b.HasIndex("RepledgeId");

                    b.ToTable("RepledgeDetails");
                });

            modelBuilder.Entity("GoldLoanFinance.Domain.Entities.RepledgeMaster", b =>
                {
                    b.Property<int>("RepledgeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RepledgeId"));

                    b.Property<int>("BankId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DatePledged")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("LoanAmountFromBank")
                        .HasPrecision(15, 5)
                        .HasColumnType("decimal(15,5)");

                    b.HasKey("RepledgeId");

                    b.HasIndex("BankId");

                    b.ToTable("RepledgeMaster");
                });

            modelBuilder.Entity("GoldLoanFinance.Domain.Entities.LoanDetails", b =>
                {
                    b.HasOne("GoldLoanFinance.Domain.Entities.LoanMaster", "LoanMaster")
                        .WithMany("LoanDetails")
                        .HasForeignKey("LoanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoanMaster");
                });

            modelBuilder.Entity("GoldLoanFinance.Domain.Entities.LoanMaster", b =>
                {
                    b.HasOne("GoldLoanFinance.Domain.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("GoldLoanFinance.Domain.Entities.RepledgeDetails", b =>
                {
                    b.HasOne("GoldLoanFinance.Domain.Entities.LoanDetails", "LoanDetails")
                        .WithMany()
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GoldLoanFinance.Domain.Entities.RepledgeMaster", "RepledgeMaster")
                        .WithMany("RepledgeDetails")
                        .HasForeignKey("RepledgeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoanDetails");

                    b.Navigation("RepledgeMaster");
                });

            modelBuilder.Entity("GoldLoanFinance.Domain.Entities.RepledgeMaster", b =>
                {
                    b.HasOne("GoldLoanFinance.Domain.Entities.Bank", "Bank")
                        .WithMany()
                        .HasForeignKey("BankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bank");
                });

            modelBuilder.Entity("GoldLoanFinance.Domain.Entities.LoanMaster", b =>
                {
                    b.Navigation("LoanDetails");
                });

            modelBuilder.Entity("GoldLoanFinance.Domain.Entities.RepledgeMaster", b =>
                {
                    b.Navigation("RepledgeDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
